"""Command-line interface (spec section 15).

    odt2web artigo.odt
    odt2web artigo.odt -o dist/
    odt2web artigo.odt --css
    odt2web artigo.odt --assets assets/
    odt2web artigo.odt --fragment
    odt2web artigo.odt --config config.yaml
    odt2web --check artigo.odt
"""
from __future__ import annotations

import argparse
import sys

from . import __version__, check, convert
from .reader import InvalidOdtError
from .result import WarningLevel


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="odt2web",
        description="Converts OpenDocument Text (.odt) documents to HTML/CSS.",
    )
    parser.add_argument("input", help="Path to the .odt file")
    parser.add_argument(
        "-o", "--output-dir", dest="output_dir", default=None,
        help="Output directory (saves index.html, style.css and assets/)",
    )
    parser.add_argument(
        "--css", dest="css", action=argparse.BooleanOptionalAction, default=None,
        help="Automatically generates CSS (default: enabled; use --no-css to disable)",
    )
    parser.add_argument(
        "--extract-images", dest="extract_images", action=argparse.BooleanOptionalAction,
        default=None, help="Extract embedded images (default: enabled)",
    )
    parser.add_argument(
        "--assets", dest="assets_dir", default=None,
        help="Subdirectory for extracted assets (default: assets)",
    )
    parser.add_argument(
        "--allow-raw-html", dest="allow_raw_html", action=argparse.BooleanOptionalAction,
        default=None,
        help="Outputs ':::html' ... ':::' blocks as literal HTML, without escaping. "
             "(default: disabled – only enable for documents from trusted authors)",
    )
    doc_group = parser.add_mutually_exclusive_group()
    doc_group.add_argument(
        "--fragment", dest="document", action="store_false", default=None,
        help="Generates only the HTML fragment (without doctype/html/head/body); "
             "without this option, a complete HTML document is generated by default.",
    )
    doc_group.add_argument(
        "--document", dest="document", action="store_true", default=None,
        help="Forces the generation of a complete HTML document (CLI default)",
    )
    parser.add_argument(
        "--config", dest="config", default=None,
        help="YAML configuration file",
    )
    parser.add_argument(
        "--check", dest="check_only", action="store_true",
        help="It only validates the document, without generating HTML.",
    )
    parser.add_argument(
        "--html-filename", dest="html_filename", default="index.html",
        help="Name of the generated HTML file within --output-dir (default: index.html)",
    )
    parser.add_argument(
        "--css-filename", dest="css_filename", default="style.css",
        help="Name of the generated CSS file within --output-dir (default: style.css)",
    )
    parser.add_argument("--version", action="version", version=f"odt2web {__version__}")
    return parser


def _print_warnings(warnings, *, file=sys.stderr) -> None:
    for warning in warnings:
        prefix = {
            WarningLevel.INFO: "info",
            WarningLevel.WARNING: "warning",
            WarningLevel.ERROR: "error",
        }.get(warning.level, "warning")
        source = f" ({warning.source})" if warning.source else ""
        print(f"[{prefix}]{source} {warning.message}", file=file)


def main(argv: list[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)

    try:
        if args.check_only:
            warnings = check(args.input)
            _print_warnings(warnings, file=sys.stdout)
            errors = [w for w in warnings if w.level == WarningLevel.ERROR]
            print(f"OK: {args.input} is a valid .odt document."
                  f"({len(warnings)} warning(s))")
            return 1 if errors else 0

        kwargs: dict = {"output_dir": args.output_dir, "config": args.config}
        if args.css is not None:
            kwargs["css"] = args.css
        if args.extract_images is not None:
            kwargs["extract_images"] = args.extract_images
        if args.assets_dir is not None:
            kwargs["assets_dir"] = args.assets_dir
        if args.allow_raw_html is not None:
            kwargs["allow_raw_html"] = args.allow_raw_html
        # unlike the API, the CLI generates a full document by default
        # (more useful for standalone use); --fragment/--document override this.
        kwargs["document"] = args.document if args.document is not None else True

        result = convert(args.input, **kwargs)
    except InvalidOdtError as exc:
        print(f"Error: {exc}", file=sys.stderr)
        return 2
    except FileNotFoundError:
        print(f"Error: file not found: {args.input}", file=sys.stderr)
        return 2

    if args.output_dir:
        result.write(args.output_dir, html_filename=args.html_filename,
                      css_filename=args.css_filename)
        print(f"Saved in {args.output_dir}/{args.html_filename}"
              + (f" e {args.output_dir}/{args.css_filename}" if result.css else ""))
    else:
        sys.stdout.write(result.html)
        if not result.html.endswith("\n"):
            sys.stdout.write("\n")

    _print_warnings(result.warnings)
    return 0


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main())
