(function () {
  "use strict";

  var form = document.querySelector("#search-form");
  var input = document.querySelector("#search-input");
  var overlay = document.querySelector("#search-overlay");
  var resultsList = document.querySelector("#search-results");
  var statusEl = document.querySelector("#search-status");
  var closeBtn = document.querySelector("#search-close");
  var header =
    document.querySelector("[data-search-header]") ||
    document.querySelector("header");

  if (!form || !input || !overlay || !resultsList) return;

  // ---------------------------------------------------------------------
  // Configuration. Can be overridden per site via data-* attributes on
  // <form id="search-form">, so this script stays generic across themes:
  //
  //   data-index-url    URL of the JSON index generated by the SSG.
  //                      Defaults to "/search-index.json".
  //   data-min-length    Minimum characters before a *live* search runs
  //                       while typing (an explicit submit always runs,
  //                       regardless of this value). Defaults to 2.
  //   data-max-results   Maximum number of results rendered. Defaults to 20.
  //
  // Expected shape of search-index.json — adjust normalizeEntry() below
  // if your generator uses different field names:
  //   [
  //     {
  //       "title": "Post title",
  //       "url": "/posts/example/",
  //       "excerpt": "Short summary...",    // optional
  //       "content": "Full plain text...",  // optional, used as fallback
  //       "tags": ["tag-a", "tag-b"]        // optional
  //     },
  //     ...
  //   ]
  // ---------------------------------------------------------------------
  var INDEX_URL = form.dataset.indexUrl || "/search-index.json";
  var MIN_QUERY_LENGTH = parseInt(form.dataset.minLength, 10) || 2;
  var MAX_RESULTS = parseInt(form.dataset.maxResults, 10) || 20;
  var DEBOUNCE_MS = 150;

  var indexPromise = null;
  var lastQuery = "";

  // -- Utilities ------------------------------------------------------------

  function debounce(fn, delay) {
    var timer = null;
    return function () {
      var context = this;
      var args = arguments;
      clearTimeout(timer);
      timer = setTimeout(function () {
        fn.apply(context, args);
      }, delay);
    };
  }

  function escapeHtml(str) {
    return String(str)
      .replace(/&/g, "&amp;")
      .replace(/</g, "&lt;")
      .replace(/>/g, "&gt;")
      .replace(/"/g, "&quot;")
      .replace(/'/g, "&#39;");
  }

  function escapeRegExp(str) {
    return str.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
  }

  // Wraps matching tokens in <mark>. Expects `text` already HTML-escaped
  // and `tokens` already lowercase, so this never introduces raw markup
  // from the index content itself.
  function highlight(escapedText, tokens) {
    if (!tokens.length) return escapedText;
    var pattern = tokens.map(escapeRegExp).join("|");
    var re = new RegExp("(" + pattern + ")", "gi");
    return escapedText.replace(re, "<mark>$1</mark>");
  }

  // Builds a short snippet around the first matched token instead of
  // dumping the whole body text into the results list.
  function buildExcerpt(body, tokens) {
    if (!body) return "";
    var lower = body.toLowerCase();
    var index = -1;
    for (var i = 0; i < tokens.length; i++) {
      var found = lower.indexOf(tokens[i]);
      if (found !== -1 && (index === -1 || found < index)) index = found;
    }
    var radius = 70;
    var start = index === -1 ? 0 : Math.max(0, index - radius);
    var end = Math.min(body.length, start + radius * 2);
    var snippet = body.slice(start, end).trim();
    if (start > 0) snippet = "…" + snippet;
    if (end < body.length) snippet += "…";
    return snippet;
  }

  // -- Index loading ----------------------------------------------------------

  function loadIndex() {
    if (!indexPromise) {
      indexPromise = fetch(INDEX_URL)
        .then(function (response) {
          if (!response.ok) throw new Error("HTTP " + response.status);
          return response.json();
        })
        .then(function (raw) {
          return (Array.isArray(raw) ? raw : []).map(normalizeEntry);
        })
        .catch(function (error) {
          console.warn("Search: failed to load " + INDEX_URL, error);
          indexPromise = null; // allow retrying on the next search
          setStatus("Could not load the search index.");
          return [];
        });
    }
    return indexPromise;
  }

  function normalizeEntry(raw) {
    return {
      title: raw.title || raw.name || "",
      url: raw.url || raw.link || "#",
      body: raw.excerpt || raw.description || raw.content || raw.body || "",
      tags: raw.tags || raw.categories || []
    };
  }

  // -- Matching / ranking -------------------------------------------------------

  function tokenize(query) {
    return query
      .toLowerCase()
      .split(/\s+/)
      .map(function (token) { return token.trim(); })
      .filter(Boolean);
  }

  function scoreEntry(entry, tokens) {
    var title = entry.title.toLowerCase();
    var body = entry.body.toLowerCase();
    var tags = entry.tags.join(" ").toLowerCase();
    var score = 0;

    tokens.forEach(function (token) {
      if (title.indexOf(token) !== -1) score += 3;
      if (tags.indexOf(token) !== -1) score += 2;
      if (body.indexOf(token) !== -1) score += 1;
    });

    return score;
  }

  function rank(entries, tokens) {
    return entries
      .map(function (entry) { return { entry: entry, score: scoreEntry(entry, tokens) }; })
      .filter(function (result) { return result.score > 0; })
      .sort(function (a, b) {
        return b.score - a.score || a.entry.title.localeCompare(b.entry.title);
      })
      .slice(0, MAX_RESULTS)
      .map(function (result) { return result.entry; });
  }

  // -- Rendering ----------------------------------------------------------------

  function renderResults(results, tokens) {
    resultsList.innerHTML = "";

    results.forEach(function (entry) {
      var li = document.createElement("li");
      var a = document.createElement("a");
      a.className = "search-result";
      a.href = entry.url;

      var title = document.createElement("span");
      title.className = "search-result__title";
      title.innerHTML = highlight(escapeHtml(entry.title), tokens);
      a.appendChild(title);

      var excerpt = buildExcerpt(entry.body, tokens);
      if (excerpt) {
        var p = document.createElement("p");
        p.className = "search-result__excerpt";
        p.innerHTML = highlight(escapeHtml(excerpt), tokens);
        a.appendChild(p);
      }

      li.appendChild(a);
      resultsList.appendChild(li);
    });
  }

  function setStatus(text) {
    if (statusEl) statusEl.textContent = text;
  }

  function describeResults(query, results) {
    var trimmed = query.trim();
    if (!trimmed) {
      setStatus("");
    } else if (results.length === 0) {
      setStatus('No results for "' + trimmed + '".');
    } else {
      setStatus(
        results.length + " result" + (results.length === 1 ? "" : "s") +
        ' for "' + trimmed + '".'
      );
    }
  }

  // -- Overlay open/close ---------------------------------------------------------

  function openOverlay() { overlay.classList.add("is-open"); }
  function closeOverlay() { overlay.classList.remove("is-open"); }
  function isOverlayOpen() { return overlay.classList.contains("is-open"); }

  // -- Search orchestration --------------------------------------------------------

  // Runs a search regardless of MIN_QUERY_LENGTH — used for explicit
  // submits (Enter / clicking the button), where the user's intent is
  // clear even for a very short query.
  function runSearch(query, openIfNeeded) {
    lastQuery = query;

    if (!query.trim()) {
      renderResults([], []);
      describeResults(query, []);
      return;
    }

    setStatus("Searching…");

    loadIndex().then(function (entries) {
      if (query !== lastQuery) return; // a newer keystroke already superseded this

      var tokens = tokenize(query);
      var results = rank(entries, tokens);

      if (openIfNeeded && !isOverlayOpen()) openOverlay();
      renderResults(results, tokens);
      describeResults(query, results);
    });
  }

  // Live search while typing: respects MIN_QUERY_LENGTH, and — this is
  // the important part — never closes the overlay. Editing the query,
  // including clearing it back to a short or empty value, only ever
  // updates what's shown inside the already-open window.
  var handleInput = debounce(function () {
    var query = input.value;
    var trimmed = query.trim();

    if (trimmed.length >= MIN_QUERY_LENGTH) {
      runSearch(query, true);
    } else if (isOverlayOpen()) {
      resultsList.innerHTML = "";
      setStatus(
        trimmed.length === 0
          ? ""
          : "Type at least " + MIN_QUERY_LENGTH + " characters to search."
      );
    }
  }, DEBOUNCE_MS);

  input.addEventListener("input", handleInput);

  // Warm up the index on first sign of intent, instead of fetching it
  // unconditionally on every page load.
  input.addEventListener("focus", function () { loadIndex(); }, { once: true });

  form.addEventListener("submit", function (event) {
    event.preventDefault();
    runSearch(input.value, true);
  });

  if (closeBtn) {
    closeBtn.addEventListener("click", closeOverlay);
  }

  overlay.addEventListener("click", function (event) {
    // Only the backdrop closes the overlay: event.target is the overlay
    // itself only when the click didn't land on a descendant (the
    // search window, its close button, or a result link).
    if (event.target === overlay) closeOverlay();
  });

  document.addEventListener("keydown", function (event) {
    if (event.key === "Escape" && isOverlayOpen()) {
      closeOverlay();
      input.focus();
    }
  });

  // -- Header height --------------------------------------------------------------
  // search.css positions the overlay right below the header using a CSS
  // custom property instead of a hardcoded pixel value, so it keeps
  // working if the header's height changes (responsive padding, a
  // longer site title wrapping to two lines, etc).

  function updateHeaderOffset() {
    if (!header) return;
    document.documentElement.style.setProperty(
      "--search-header-height",
      header.getBoundingClientRect().height + "px"
    );
  }

  updateHeaderOffset();
  window.addEventListener("resize", debounce(updateHeaderOffset, 150));
})();